name: Build & Package STUSD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-cryptonote:
    name: Build cryptonote-core (C++)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install C++ dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git \
            libboost-all-dev libssl-dev libzmq3-dev \
            libcurl4-openssl-dev pkg-config curl

      - name: Clone Monero core
        run: |
          mkdir -p cryptonote-core/src/monero
          git clone --depth 1 https://github.com/monero-project/monero.git cryptonote-core/src/monero

      - name: Build STUSD daemon
        working-directory: cryptonote-core/src/monero
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Collect binaries
        run: |
          mkdir -p cryptonote-core/build-output
          cp cryptonote-core/src/monero/build/stashusd cryptonote-core/build-output/
          cp cryptonote-core/src/monero/build/stashusd-wallet-cli cryptonote-core/build-output/

  build-erc20:
    name: Compile ERC20/TRC20 contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        working-directory: eth-trc20-token
        run: npm install

      - name: Compile contracts with Hardhat
        working-directory: eth-trc20-token
        run: npx hardhat compile

  package-artifact:
    name: Package & Upload ZIP
    needs:
      - build-cryptonote
      - build-erc20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Gather build outputs
        run: |
          mkdir -p release/artifact
          # C++ binaries
          cp cryptonote-core/build-output/* release/artifact/
          # Solidity artifacts
          cp -r eth-trc20-token/artifacts release/artifact/contracts
          # Bridge server, docs, wallets
          cp -r bridge-server release/artifact/
          cp -r docs release/artifact/
          cp -r wallets release/artifact/

      - name: Create ZIP package
        run: |
          cd release
          zip -r stash-usd-release.zip artifact

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: stash-usd-release
          path: release/stash-usd-release.zip

